# To start docker-compose run
# sudo docker-compose -f mysql.yml up -d
#

mysql:
  container_name: mysql-library
  image: "mysql:5.7"
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: library
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    ssl-mode: DISABLED